# Generated by Django 5.1.2 on 2024-10-27 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image_path', models.CharField(max_length=255)),
                ('face_encoding', models.JSONField()),
                ('scan_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
