# Generated by Django 5.1.2 on 2024-10-29 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_api', '0002_apiadmin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiadmin',
            name='phone_number',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
