# Generated by Django 5.1.2 on 2024-10-29 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_api', '0003_alter_apiadmin_phone_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ApiAdmin',
        ),
    ]
