# Generated by Django 5.1.2 on 2024-10-31 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_api', '0005_searchrecord'),
    ]

    operations = [
        migrations.RenameField(
            model_name='searchrecord',
            old_name='name',
            new_name='student_id',
        ),
    ]
