# Generated by Django 5.1.2 on 2024-10-31 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_api', '0006_rename_name_searchrecord_student_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserImage',
            new_name='Students',
        ),
    ]
