# Generated by Django 5.1.2 on 2024-10-31 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_api', '0007_rename_userimage_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchrecord',
            name='student_id',
        ),
        migrations.AddField(
            model_name='searchrecord',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='search_records', to='student_api.students'),
            preserve_default=False,
        ),
    ]
