# Generated by Django 5.1.2 on 2024-11-07 05:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_api', '0008_remove_searchrecord_student_id_searchrecord_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchrecord',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='search_records', to='student_api.students'),
        ),
    ]
