# Generated by Django 5.1.2 on 2025-01-29 07:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_api', '0009_alter_searchrecord_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
