# Generated by Django 5.1.2 on 2025-01-30 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_api', '0010_students_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='identifier',
            field=models.CharField(default=11, max_length=255),
            preserve_default=False,
        ),
    ]
