# Generated by Django 5.1.2 on 2025-01-30 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_api', '0011_students_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='identifier',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
