# Generated by Django 5.1.2 on 2025-01-31 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_api', '0012_alter_students_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='identifier',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
