# Generated by Django 5.1.2 on 2025-02-03 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_api', '0013_alter_students_identifier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='students',
            name='identifier',
        ),
    ]
