# Generated by Django 5.1.2 on 2025-02-03 07:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_api', '0014_remove_students_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='students',
            name='identifier',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
